version: "3"
services:
  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=decision-bot
      - POSTGRES_USER=decision-bot
      - POSTGRES_PASSWORD=decision-bot

  backend:
    image: backend:latest
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_DB=decision-bot
      - POSTGRES_USER=decision-bot
      - POSTGRES_PASSWORD=decision-bot
      - dev=production
    ports:
      - "0.0.0.0:80:8000"
    command:
      - /bin/bash
      - -c
      - |
        cd /usr/src/app
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000